// src/js/constants/action-types.js
// GET all repositories from Github
export const FETCH_REPOSITORIES_PENDING = "FETCH_REPOSITORIES_PENDING";
export const FETCH_REPOSITORIES_SUCCESS = "FETCH_REPOSITORIES_SUCCESS";
export const FETCH_REPOSITORIES_FAILURE = "FETCH_REPOSITORIES_FAILURE";

// GET all saved bookmarks
export const FETCH_BOOKMARKS_PENDING = "FETCH_BOOKMARKS_PENDING";
export const FETCH_BOOKMARKS_SUCCESS = "FETCH_BOOKMARKS_SUCCESS";
export const FETCH_BOOKMARKS_FAILURE = "FETCH_BOOKMARKS_FAILURE";

//
export const POST_BOOKMARK_PENDING = "POST_BOOKMARK_PENDING";
export const POST_BOOKMARK_SUCCESS = "POST_BOOKMARK_SUCCESS";
export const POST_BOOKMARK_FAILURE = "POST_BOOKMARK_FAILURE";

//
export const DELETE_BOOKMARK_PENDING = "DELETE_BOOKMARK_PENDING";
export const DELETE_BOOKMARK_SUCCESS = "DELETE_BOOKMARK_SUCCESS";
export const DELETE_BOOKMARK_FAILURE = "DELETE_BOOKMARK_FAILURE";